### ISSUE TITLE
add before/after hooks

### ISSUE THREAD

**Issue by hlozancic** [rhwilr/adonis-bumblebee#11]
Currently on a project that I'm working on, we have implemented our custom transformers for data and we have logic to do something before transformation of each resource begin.

We use this to populate **likes** data for each home (user can like homes on our site). Before hook was made so we query likes table only once even if we are returning list of 20 homes per page...

This is part of our implemntation showing how we reuse one query data to populate a list of homes with user likes... So only two queries will happen. One that queries 20 homes, and one that queries likes of users for ids of homes in that 20 list.

```
class HomePopulator extends BasePopulator {

    async beforeHook(model, ctx, meta) {
        const currentUser = ctx.getUserId()
        // here we fetch all like metadata, using whereIn query (**thanks to before hook**)
        meta._likes = await HomeLike.query()
            .select(['home_id', 'type']) // we have likes, and type of like (happy smile, angry smile, etc...)
            .count('type as count')
            .whereIn('home_id', model.rows ? model.rows.map(o => o.id) : model.id)
            .groupBy(['home_id', 'type'])
        meta._likes = _.mapValues(_.groupBy(meta._likes, 'home_id'), value => _.map(value, i => _.pick(i, ['type', 'count'])))

        // also we are fetching data if currently logged in user already liked something from the list...
        meta._myLike = currentUser && await HomeLike.query()
            .whereIn('home_id', model.rows ? model.rows.map(o => o.id) : model.id)
            .where('user_id', currentUser)
        meta._myLike = _.keyBy(meta._myLike, 'home_id')

        return model
    }

     // this is almost identical logic as bumblebee transform...
    async populate(model, ctx, meta) {

        let payload = {
            id: model.id,
            slug: model.slug,
            title: model.title,
            // .... other key/values
        }

        // but here we can access before hook data, and connect data without queries...
        payload.likes = meta._likes[model.id]
        payload.myLike = meta._myLike[model.id] && meta._myLike[model.id].type

        return payload
    }
}
```

**Comment by rhwilr** [comment]
I don't quite get what your suggestion is. Are you requesting a method to define hooks that are called before and after a transform?

**Comment by hlozancic** [comment]
Exactly!

In my example... I'm returning list of homes to user together with like information. Currently to achive this with Bumblebee I would need to query like data for each house in the list.

By using before hook, we could do query that would gather information about likes for all homes that will pass through transformer. And then inside transform method we would reuse that information to assign this data to currently transformed instance without need to query like data for that information.

I hope I explained it well :) If not, I'll create better example for you later...

**Comment by rhwilr** [comment]
Going by your example, I'm not sure you really need a hook for this.
You do know all the data that is going to be transformed, since you are passing it to the transformer. Why cant you just attach the likes to a property on your model before passing it to the transformer.

I will think about it a bit more to decide if a hook system can come in use in other places. But it is going to be low in priority. Probably one or two releases out.

But feel free to submit a PR if you need this feature.

**Comment by rhwilr** [comment]
I will close this issue since there does not seem to be much demand for this feature.
If anyone still needs this, feel free to leave suggestions or submit a PR.
