### ISSUE TITLE
.paginate can't call getRelated method

### ISSUE THREAD

**Issue by hlozancic** [rhwilr/adonis-bumblebee#13]
As the title says, it seams like it's impossible to transform related content if using .paginate() instead, for example, .collection().

This will work (but it will not return adonis pagination info):
```
const posts = await Posts.query().with('tags').paginate()
transform.include('tags').collection(posts, PostTransformer)
```

This will not work:
```
const posts = await Posts.query().with('tags').paginate()
transform.include('tags').paginate(posts, PostTransformer)
```

Error thrown is: model.getRelated is not a function... PostTransformer has this include:
```
includeTags(model) {
        return this.collection(model.getRelated('tags'), TagTransformer)
    }
```

Without .include() and defaultIncludes inside transformer, .paginate() works as expected

**Comment by rhwilr** [comment]
This issue was fixed by @spamoom in #14
