### ISSUE TITLE
eagerloadIncludedResource tries to load when not needed

### ISSUE THREAD

**Issue by hlozancic** [rhwilr/adonis-bumblebee#16]
Let's say that we have users who have avatar image relation in another media table.

User is not required to have avatar uploaded, so sometimes this relation can be NULL.

If you do the query:
```const users = await User.query().with('avatar').fetch()```
And then afterwards you transform it via transformer
```transform.include('avatar').collection(users, UserTransformer)```

Bumbleebee will inside TransformerAbstract eagerloadIncludedResource try to loadMany avatar for each user that has this realtion as NULL.

Suggestion:
eagerloadIncludedResource filter should change from:
```return (data[resource] instanceof Function) && !data.getRelated(resource)```
to: 
```return (data[resource] instanceof Function) && !data.getRelated(resource) && data.$relations[resource] !== null```

**Comment by rhwilr** [comment]
Would you mind submitting a PR for this with a test case?

**Comment by hlozancic** [comment]
Ok, will do... Currently in a deadline rush so I'll try to submit as soon I get free time.

It's very easy to see the issue with DB_DEBUG=true in .env...

**Comment by rhwilr** [comment]
This issue has been fixed in [v1.4.0](https://github.com/rhwilr/adonis-bumblebee/releases/tag/1.4.0).
