### ISSUE TITLE
Namespaced Transformers Support

### ISSUE THREAD

**Issue by NeroOficial** [rhwilr/adonis-bumblebee#24]
Hi, again...

I think is good to implement a way for developers create transformers inside Folders.

E.g. User Run: `adonis make:transformer Products/Product`

The output should be a file inside the folder `app/Transformers/Products/ProductTransformer.js`

So, i've  just created a Pull Request supporting this feature.

**Comment by rhwilr** [comment]
Thanks for your PR https://github.com/rhwilr/adonis-bumblebee/pull/23. :smiley: :+1:
