### ISSUE TITLE
How to access to pivot table data?

### ISSUE THREAD

**Issue by vincentducorps** [rhwilr/adonis-bumblebee#27]
Hello :)

I have 3 tables :
- users
- skills
- user_skill (pivot table)

In user_skill (the pivot table) I have a field for the level (rank) of the user on this skill.

How to get this field in my transformer?
Thanks

**_CODE BELLOW DOESN'T WORK_**

"Cannot read property 'rank' of undefined"

## Model 
```` js
class User extends Model {
  skills() {
    return this.belongsToMany('App/Models/Skill')
      .pivotTable('user_skill')
      .withPivot(['rank'])
  }
}
````

## Controller 
```` js
class UserController {
    async show({ params, request, response, transform }) {
        let user = await User.find(params.id)

        if (!user) {
          return response.status(404).json({ data: 'Resource not found' })
        }

        await user.loadMany(['skills'])

        return transform.include(['skills']).item(user, UserTransformer)
  }
}
````

## Transformer
```` js
class UserTransformer extends TransformerAbstract {
  availableInclude() {
    return [
      'skills'
    ]
  }

  transform(user) {
    return {
      id: user.id,
      firstname: user.firstname,
      lastname: user.lastname
    }
  }

  includeSkills(user) {
    return this.collection(user.getRelated('skills'), skill => ({
        id: skill.id,
        name: skill.name,
        rank: skill.pivot.rank
    }))
}
````

**Comment by rhwilr** [comment]
The `pivot` property is not on the model its self. You have to access it through the `$relations` property.

So this should work: 
```js
  includeSkills(user) {
    return this.collection(user.getRelated('skills'), skill => ({
        id: skill.id,
        name: skill.name,
        rank: skill.$relations.pivot.rank
    }))
```

Or at least that is how I've done it in my app. But I just searched the adonis documentation and can't find any information on how to access pivot data at all.

Please correct me, if I'm missing something.

**Comment by vincentducorps** [comment]
Thank you for your answer. It's works!

Maybe you should keep this issue open (tag with "question"?) if someone wants to contribute.

Have you asked how to access pivot data on the official adonis-lucid repo?

**Comment by rhwilr** [comment]
I will keep it open for a while. 
No, I haven't had time to look into it further. But if you or someone else wants to look into it, feel free to link to this issue.

**Comment by dschreij** [comment]
Isn't it the case just to prefix the variable with `pivot_`? At least that is the Laravel way, and it also seems to work in adonisjs for me:

So if you have a variable `status_id` on the pivot table between posts and tags, you could access it by
```javascript
const post = Post.find(1)
const tag = post.tags().withPivot(['status_id']).first()
const status_id = tag.pivot_status_id
```
This is with Adonis 4.1 at least.
