### ISSUE TITLE
JSONAPI compliant serializer

### ISSUE THREAD

**Issue by jsdecena** [rhwilr/adonis-bumblebee#30]
Hi. First, thank you for such a nice library for transforming our data.

Do you think you can create another default serializer for JSONAPI compatible format? It would be nice if we can use: https://github.com/SeyZ/jsonapi-serializer as one of the adonijs compatible serializer. :)

**Comment by rhwilr** [comment]
I tried to create a JSONAPISerializer but to fully support JSONAPI we would have to make many changes to the architecture of bumblebee which I am currently not willing to do. 
I suggest you use the [SeyZ/jsonapi-serializer](https://github.com/SeyZ/jsonapi-serializer) library you linked. It seems to already fully support JSONAPI.
