### ISSUE TITLE
Includes don't work for many to many relations

### ISSUE THREAD

**Issue by TwoLiquid** [rhwilr/adonis-bumblebee#31]
Hi guys! Now I'm creating my first project with adonisJS and in fact i enjoy it at all, but there is a problem with bumblebee transformer and i could not find any solution for that. When I use "include" method in transformer for many to many relations - it doesn't work and there is no kind of error, it just ignores relations. I'm doing all straight by docs, "include" works for belongsTo relations and doesn't work for "pivot table" to get all related entities for transforming model. Can you help me and describe why it does't it work properly with many to many relation, how could you miss that moment (i don't believe you could, but it seems to me that it's a pure fact) and which solution for many to many relations in transformer i can get out from box? Thank you!

**Comment by TwoLiquid** [comment]
Finally i have found the solution - just remove "static get" before include${relation}... damn...

**Comment by rhwilr** [comment]
I'm sorry. This might have been my fault. The documentation in the repository shows changes for the upcoming 2.0 release. I will fix this shortly.
Hope you enjoy adonis and my bumblebee addon.

**Comment by TwoLiquid** [comment]
Thank you! I really enjoy adonis and your addon and wish you good luck with it)

**Comment by nperegrine** [comment]
Thanks a lot, @TwoLiquid ... I spent hours trying to figure this out too. I think it would be great to mention this in the docs (removing the "static get" in front of defaultInclude() in transformer class,) in the case of Many to Many Relationships because the "static get" gives errors.
