### ISSUE TITLE
A transformer must be a function or a class extending TransformerAbstract

### ISSUE THREAD

**Issue by kmorpex** [rhwilr/adonis-bumblebee#69]
Sometimes i see this error, but I do not understand why the error appears and disappears. Sometimes this is decided by a rebuild

Error: A transformer must be a function or a class extending TransformerAbstract
    at Scope._getTransformerInstance (/app/node_modules/adonis-bumblebee/src/Bumblebee/Scope.js:204:11)
    at Scope._fireTransformer (/app/node_modules/adonis-bumblebee/src/Bumblebee/Scope.js:121:38)
    at Scope._executeResourceTransformers (/app/node_modules/adonis-bumblebee/src/Bumblebee/Scope.js:93:52)
    at <anonymous>

**Comment by rhwilr** [comment]
This looks like an error in your code. The error message indicates that you might be calling the transform method with a wrong argument.
Please check your controllers, specifically the `transform.collection`, `transform.paginate` and `transform.item` calls, where the second argument should always be a transformer instance.

Otherwise, I can't really help you without any code or examples that produce the error.

**Comment by kmorpex** [comment]
> This looks like an error in your code. The error message indicates that you might be calling the transform method with a wrong argument.
> Please check your controllers, specifically the `transform.collection`, `transform.paginate` and `transform.item` calls, where the second argument should always be a transformer instance.
> 
> Otherwise, I can't really help you without any code or examples that produce the error.

`async getAll ({ request, response, transform }) {
    const certificates = await CertificateRepository.getAll(request.get())
    return transform.include('rate,customer').paginate(certificates, CertificateTransformer)
  }
  /**
   *
   * Get method
   *
   * @param request
   * @param params
   * @param response
   * @param transform
   * @returns {Promise<*|Promise<any>>}
   */
  async get ({ request, params, response, transform }) {
    const certificate = await CertificateRepository.findById(params.id)
    return transform.include('rate.services,partner,subdivision,agent,customer,region,clients').item(certificate, CertificateTransformer)
  } `

**Comment by rhwilr** [comment]
Assuming you are importing the `CertificateTransformer`, this looks right.
If you find a reproducible case that produces the error I can take a look, but I can't help you debug this with this little information.

**Comment by kmorpex** [comment]
Ok, sorry. I just don’t understand what the problem is, since the same version can give this error or not

```javascript
'use strict'

const TransformerAbstract = use('Adonis/Addons/Bumblebee/TransformerAbstract')
const ClientTransformer = use('App/Transformers/ClientTransformer')
const RateServiceTransformer = use('App/Transformers/RateServiceTransformer')
const RateTransformer = use('App/Transformers/RateTransformer')
const PartnerTransformer = use('App/Transformers/RegionTransformer')
const RegionTransformer = use('App/Transformers/RegionTransformer')
const SubdivisionTransformer = use('App/Transformers/SubdivisionTransformer')
const AgentTransformer = use('App/Transformers/AgentTransformer')

/**
 * CertificateTransformer class
 *
 * @class CertificateTransformer
 * @constructor
 */
class CertTransformer extends TransformerAbstract {
  
  static get availableInclude () {
    return [
      'region',
      'agent',
      'partner',
      'subdivision',
      'rate',
      'customer',
      'clients',
      'services'
    ]
  }

  /**
   * This method is used to transform the data.
   */
  transform (model) {
    return {
      id: model.id,
      authId: model.auth_id,
      rateId: model.rate_id,
      number: model.number,
      cost: model.cost,
      type: model.type,
      startDate: model.start_date,
      finishDate: model.finish_date,
      active: model.active,
      blocked: model.blocked,
      blockDate: model.block_date,
      createdAt: model.created_at
    }
  }

  includeClients (model) {
    return this.collection(model.getRelated('clients'), ClientTransformer)
  }

  includeRate (model) {
    return this.item(model.getRelated('rate'), RateTransformer)
  }

  includeServices (model) {
    return this.item(model.getRelated('service'), RateServiceTransformer)
  }

  includeRegion (model) {
    return this.item(model.getRelated('region'), RegionTransformer)
  }

  includeCustomer (model) {
    return this.item(model.getRelated('customer'), ClientTransformer)
  }

  includeAgent (model) {
    return this.item(model.getRelated('agent'), AgentTransformer)
  }

  includePartner (model) {
    return this.item(model.getRelated('partner'), PartnerTransformer)
  }

  includeSubdivision (model) {
    return this.item(model.getRelated('subdivision'), SubdivisionTransformer)
  }

}

module.exports = CertTransformer;

```

**Comment by rhwilr** [comment]
The exception is thrown here: https://github.com/rhwilr/adonis-bumblebee/blob/master/src/Bumblebee/Scope.js#L204

We check if the parameter is a string for a class, a transformer instance, or a function that is then turned into a transformer. This might help you in debugging.

**Comment by kmorpex** [comment]
I was changed 
const BumblebeeTransformer = use('Bumblebee/Transformer')
to
const TransformerAbstract = use('Adonis/Addons/Bumblebee/TransformerAbstract')

And the problem was solved
