### ISSUE TITLE
Suggestion: return array of strings after transform

### ISSUE THREAD

**Issue by hlozancic** [rhwilr/adonis-bumblebee#9]
For example I have TagTransformer which should return tags as array of tag.title strings like:
`tags: ['tag1', 'tag2', 'tag3' ... ]`

Currently it's only possible to return array of tag objects like:
`tags: [{title: 'tag1'}, {title: 'tag2'}, {title: 'tag3'} ...]`

**Comment by rhwilr** [comment]
If this is in an include function you can just return an array from there instead of using the `collection` method.
But i will check what it would take to allow a transformer to return arrays and primitive types.

**Comment by rhwilr** [comment]
@hlozancic I just made made a small change to allow a transformer to return primitive types. Would be awesome if you could check it out by installing from master (a17399736b9342c4796e8467ac7a5022aaff804e) and give feedback if this satisfies your needs.

**Comment by hlozancic** [comment]
Yeah! That's it :)

👍

**Comment by rhwilr** [comment]
Is available in v1.1.0
